### ISSUE TITLE
Surfaces are occasionally missed.

### ISSUE THREAD

**Issue by nathanielfernandes99** [kovacsv/occt-import-js#42] opened 2024-08-18 23:59 UTC
Some surfaces are not meshed. See
[example.zip](https://github.com/user-attachments/files/16653283/example.zip). When opening it inside CAD software, all surfaces are displayed.

**Comment by chriskuech** [comment] 2024-11-29 07:13
I'm facing this issue as well. Any idea what's happening with the dropped faces?

**Comment by chriskuech** [comment] 2024-11-29 16:29
I am also not able to reproduce the issue in https://3dviewer.net/

**Comment by nathanielfernandes99** [comment] 2024-11-29 20:11
I cant figure it out, it only seems to happen sometimes with cone surfaces.

**Comment by nathanielfernandes99** [comment] 2024-11-29 20:13
The test step i attached has the conical surface missing when using 3dviewer.net

**Comment by nathanielfernandes99** [comment] 2024-12-02 21:30
Okay great!

Let me know when you think you have it fixed.

**Comment by kovacsv** [comment] 2024-12-03 07:15
Fixed in the latest release.

**Closed** 2024-12-03 07:15 UTC
